### ISSUE TITLE
Request for Information for Mod Compatibility - EvolvedOrgansRedux

### ISSUE THREAD

**Issue by Xahkarias** [Aurani/EPOE-Forked#1]
Hello, I am the creator of [EvolvedOrgansRedux ](https://github.com/Xahkarias/EvolvedOrgansRedux), and I was wondering if we could work together to add compatibility between our mods. It would be great if you could send me a list of changes that EPOE Forked contains so that I can see what is potentially a gap in compatibility. Thank you.

**Comment by Tarojun** [comment]
To describe briefly what EPOE-Forked adds:
Seeing that you specifically have a patch for RBSE, in essence, EPOE is mechanically similar to it, minus the organ rotting and rejection stuff. Simply different balances and production method of the prothesis.
And that we recently added some augment options that does not trigger body purists, but transhumanists hates it instead. The  concept is that the organic optimizer nanobots bring out the latent potential of a natural body part.
